### ISSUE TITLE
PHPUnit is a non-dev dependency

### ISSUE THREAD

**Issue by ms2ad** [zetacomponents/Feed#10]
`zetacomponents/feed` is part of a current project via another dependency. In contrast to your other packages like 

https://github.com/zetacomponents/SystemInformation/blob/ede40804f9ab549465e2e429836614bd79a313fd/composer.json#L48

`phpunit/phpunit` is a non-dev dependency

https://github.com/zetacomponents/Feed/blob/cbbf29782bc1c6511204e2aa085301fafaac37c3/composer.json#L51

so that will be installed in a version `~9.0` as a requirement of this package and the main application also cannot use PHPUnit 10.

**Comment by ms2ad** [comment]
@derickr Are there any plans for a new release in the near future?

**Comment by derickr** [comment]
Done.

**Comment by ms2ad** [comment]
@derickr Thank you very much!
